sudo: true
language: node_js
node_js:
  - '9'
os: osx
install:
  - npm install -g node-gyp
  - npm install -g electron-packager
  - npm install
  - electron-packager . minerstat --overwrite --platform=darwin --arch=x64 --icon=asset/logo.icns --prune=true --out=release-builds
before_deploy:
  - cd release-builds/minerstat-darwin-x64
  - zip -r minerstat-asic-mac.zip .
  - git config --local user.name "coinscrow"
  - git config --local user.email "hello@coinscrow.io"
  - if [ -z "$TRAVIS_TAG" ] ; then TRAVIS_TAG=1.0; fi
deploy:
  provider: releases
  api_key:
    secure: M5RNpQtRw6O3RCpr8hFd3pg8XtyfOUthHM5cBL0dPr8kQpBIDeMUGANliEdxEcEm7neN8PbnxDcTzVrysQUFkDzsvQ6fd3iHy9RiF8c6ZSfhOnRdr3oA3URjd6Iso6Y83svAb2xGo5fsCgOIv36krne7hTfniGGxn/eCUcc48IpXSX3nd+JLoUwnL0U5QKcwAYSP6WSDmrWAPcfAmnoz5kV3KvWz0tX4ZU++MrjVufbiWUhSI7dGRKED8q6bJKTZbOW/x3ExD6QQN0VqdNOllsPufYkwYTBKJ+v+D+FqqhHKe4kl6B6kH4bTRJNudDblNnRoQFTzeAtzEK6T5nAmoSEcExrAenReuSUY0mpKg7LcP9FTGo1K2NSbHBQ+fBGjT2X+2GFYjBRfybkA59DgZVhMkt0H4QV9yFu/zbsjZTrghc721L1n4Ip68DgMtvcAqB1ImyWVq9XwS3qu1zJwNJm/07bd1oQ7o5+9ZF9sbiX1UXf2p0H/34lN6pf37otPMAMOi+acoectdLrdNRsskdA3I+KMkucnVmtioqiq1kBovJl6J7zDbbKZ0Uo76rwhnvCAgKDgyZzeARrBI9YQL8kfs98q6/WiBcHsFUuXWOVA3N6D9eunH+wpiEmvrcVG8RAcbnjK6xPus1vJakfa2igZCuCgG0VIaxP6RcOjytI=
  file: "$TRAVIS_BUILD_DIR/release-builds/minerstat-darwin-x64/minerstat-asic-mac.zip"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  draft: false
  on:
    tags: false
    branch: master
